Update rollback.yml

diff --git a/.github/workflows/rollback.yml b/.github/workflows/rollback.yml
--- a/.github/workflows/rollback.yml
+++ b/.github/workflows/rollback.yml
@@ -49,8 +49,20 @@ jobs:
         # Output the ARN of the N-1 revision
         echo "Previous Task Definition: $PREVIOUS_TASK_DEF"
 
-        # Set output variable to be used in subsequent steps
-        echo "TASK_DEFINITION_ARN=$PREVIOUS_TASK_DEF" >> $GITHUB_ENV
+        # Check if PREVIOUS_TASK_DEF is empty or None
+        if [ -z "$PREVIOUS_TASK_DEF" ] || [ "$PREVIOUS_TASK_DEF" == "None" ]; then
+          echo "No previous task definition found. Exiting."
+          exit 1
+        fi
+
+        # Clean up PREVIOUS_TASK_DEF (remove any unwanted characters)
+        PREVIOUS_TASK_DEF=$(echo "$PREVIOUS_TASK_DEF" | tr -d '\r' | tr -d '\n')
+
+        # Write to $GITHUB_ENV
+        echo "TASK_DEFINITION_ARN=\"$PREVIOUS_TASK_DEF\"" >> $GITHUB_ENV
+
+        # Verify that TASK_DEFINITION_ARN is correctly set
+        echo "TASK_DEFINITION_ARN is now: $TASK_DEFINITION_ARN"
 
     - name: Update ECS Service with N-1 Task Definition
       run: |
